title: Anthony Chen # your name (or website title) here


![Me](./images/Self.png)
#<img src="https://user-images.githubusercontent.com/achen004/achen004.github.io/images/master/Self.png"/>
#<img src="https://github.com/achen004/achen004.github.io/images/master/Self.png"/>
#"images/Selfie.png?raw=true" # ![Me]( {{https://achen004.github.io/}}images/Selfie.png ) #

description: > # your text below (remove <br> elements if you don't need line breaks)
  <br>
  
  Since my undergraduate education, I have had an interest in applying statistics in a business setting. With my continued passion for knowledge, I decided to further pursue mastery in data science, ML, and AI. My work experience in both industry and academia shows that I am well-equipped with not only analytical tools, but also a versatile background. I also demonstrate a strong time management ability due to balancing both work and school. 
  
  </br>
  
  
  In my free time I enjoy playing basketball, jogging, and watching fútbol highlights.
  
  
  <a href="https://www.linkedin.com/in/chen-anthony/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
